# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
    - 'CS/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'CS/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./CS/CS.sln
    - name: Build
      run: dotnet build ./CS/DayOne/Day1.csproj --configuration Release --no-restore
    - name: Build
      run: dotnet build ./CS/DayTwo/Day2.csproj --configuration Release --no-restore
    - name: Build
      run: dotnet build ./CS/DayThree/Day3.csproj --configuration Release --no-restore
    - name: Build
      run: dotnet build ./CS/DayFour/Day4.csproj --configuration Release --no-restore
    - name: Build
      run: dotnet build ./CS/Day5/Day5.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./CS/CS.sln --configuration Release --no-restore
